### ISSUE TITLE
Option to have a popped task per hopper, or even hopper sets

### ISSUE THREAD

**Issue by rstrohmh** [chao-mu/random-hopper#5]
I'd find it useful to be able to have a popped task per hopper or maybe sets of hoppers that funnel to a popped task, because my hoppers are all very different sets of things. Work vs. personal tasks, or "things I can do from my phone" vs. "things that require my full workshop."

This might conflict with the "limit the overwhelming task list" concept though, so if added it should probably be a non default option.

**Comment by chao-mu** [comment]
What if instead of pinning tasks, you pin hoppers (still one at a time). When you pin a hopper, it has a pinned task that is displayed which you can exchange for a different one.

**Comment by chao-mu** [comment]
Okay, released hopper pinning.  Let me know what you think. Thank you so much for filing this ticket!
